export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS',
  ORDER_INSUFFICIENT_STOCK = 'ORDER_INSUFFICIENT_STOCK',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND',
  INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT',
  INVENTORY_ADJUSTMENT_FAILED = 'INVENTORY_ADJUSTMENT_FAILED',
  IDEMPOTENCY_REPLAY = 'IDEMPOTENCY_REPLAY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  DUPLICATE_ENTITY = 'DUPLICATE_ENTITY',
  INVALID_OPERATION = 'INVALID_OPERATION',
}

export const ErrorMessages: Record<ErrorCode, string> = {
  [ErrorCode.INTERNAL_ERROR]: 'Internal server error',
  [ErrorCode.VALIDATION_ERROR]: 'Validation failed',
  [ErrorCode.NOT_FOUND]: 'Resource not found',
  [ErrorCode.CONFLICT]: 'Resource conflict',
  [ErrorCode.FORBIDDEN]: 'Access denied',
  [ErrorCode.UNAUTHORIZED]: 'Unauthorized',
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 'Token has expired',
  [ErrorCode.AUTH_TOKEN_REVOKED]: 'Token has been revoked',
  [ErrorCode.TENANT_REQUIRED]: 'Tenant ID is required',
  [ErrorCode.ORDER_NOT_FOUND]: 'Order not found',
  [ErrorCode.ORDER_INVALID_STATUS]: 'Invalid order status transition',
  [ErrorCode.ORDER_INSUFFICIENT_STOCK]: 'Insufficient stock for order',
  [ErrorCode.PAYMENT_FAILED]: 'Payment processing failed',
  [ErrorCode.PRODUCT_OUT_OF_STOCK]: 'Product is out of stock',
  [ErrorCode.PRODUCT_NOT_FOUND]: 'Product not found',
  [ErrorCode.CUSTOMER_NOT_FOUND]: 'Customer not found',
  [ErrorCode.SUPPLIER_NOT_FOUND]: 'Supplier not found',
  [ErrorCode.INVENTORY_INSUFFICIENT]: 'Insufficient inventory',
  [ErrorCode.INVENTORY_ADJUSTMENT_FAILED]: 'Inventory adjustment failed',
  [ErrorCode.IDEMPOTENCY_REPLAY]: 'Request already processed',
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 'Too many requests, please try again later',
  [ErrorCode.INTEGRATION_ERROR]: 'External integration failed',
  [ErrorCode.DUPLICATE_ENTITY]: 'Entity already exists',
  [ErrorCode.INVALID_OPERATION]: 'Operation not allowed in current state',
};
